# Use the official Debian Bookworm base image
FROM debian:bookworm-slim

# Configure default editor
ENV EDITOR=nano

# We make a fake systemctl so that incus doesn't error out without systemd
RUN echo "deb http://deb.debian.org/debian bookworm contrib" >> /etc/apt/sources.list && \

    # Install curl so we can install the keyring.
    apt-get update && \
    apt-get install --no-install-recommends -y curl ca-certificates && \
    mkdir -p /etc/apt/keyrings/ && \
    curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc && \
    echo "deb [signed-by=/etc/apt/keyrings/zabbly.asc] https://pkgs.zabbly.com/incus/stable $(. /etc/os-release && echo ${VERSION_CODENAME}) main" > /etc/apt/sources.list.d/zabbly-incus-stable.list && \

    # Install incus and so on
    apt-get update && \
    apt-get install --no-install-recommends -y \
        fuse nftables ebtables arptables iproute2 \
        thin-provisioning-tools openvswitch-switch \
        btrfs-progs lvm2 udev iptables kmod nano vim tini && \

    apt-get install --no-install-recommends --no-install-suggests -y \
        zfsutils-linux && \

    apt-get install --no-install-recommends -y \
        incus incus-ui-canonical && \

    apt autoremove -y && \
    apt-get clean

COPY --chown=root:root --chmod=755 start.sh /start.sh

# Set environment variables
ENV PATH="/opt/incus/bin/:$PATH"
ENV INCUS_EDK2_PATH="/opt/incus/share/qemu/"
ENV LD_LIBRARY_PATH="/opt/incus/lib/"
ENV INCUS_LXC_TEMPLATE_CONFIG="/opt/incus/share/lxc/config/"
ENV INCUS_DOCUMENTATION="/opt/incus/doc/"
ENV INCUS_LXC_HOOK="/opt/incus/share/lxc/hooks/"
ENV INCUS_AGENT_PATH="/opt/incus/agent/"
ENV INCUS_UI="/opt/incus/ui/"

# Run the incusd binary
CMD ["/usr/bin/tini" "/start.sh"]
